### ISSUE TITLE
Installing spacy_iwnlp fails

### ISSUE THREAD

**Issue by Frobless** [Liebeck/spacy-iwnlp#4]
`pip install spacy-iwnlp` fails with the error:
Failed to build spacy
ERROR: Could not build wheels for spacy, which is required to install pyproject.toml-based projects
I was able to install spacy by `pip install spacy` but I'm not able to install iwnlp. What could be the problem?

**Comment by Liebeck** [comment]
@Frobless I finally updated to spaCy 3. I know it's a bit late, but it should work now.
